/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.kpihx_lab.contacts_manager.frames;

import java.util.ArrayList;

import com.kpihx_lab.contacts_manager.core.*;

/**
 *
 * @author kpihx
 */
public class ContactsDisplayFrame extends javax.swing.JFrame {
    private MainFrmApplication mainFrmApplication;
    private Repertoire repertoire;
    private String[] repertoireAgentsLabel = Agent.getRepertoireAgentsLabel();
    private String[] repertoireEnseignantsLabel = Enseignant.getRepertoireEnseignantsLabel();
    private String[] repertoireEtudiantsLabel = Etudiant.getRepertoireEtudiantsLabel();
    private String[][] repertoireAgents;
    private String[][] repertoireEnseignants;
    private String[][] repertoireEtudiants;
    
    /** Creates new form ContactsDisplayFrame */
    public ContactsDisplayFrame(MainFrmApplication mainFrmApplication) {
        this.mainFrmApplication = mainFrmApplication;
        this.repertoire = mainFrmApplication.getRepertoire();
        
        String[][][] sousRepertoires = repertoire.sousRepertoires();
        repertoireAgents = sousRepertoires[0];
        repertoireEnseignants = sousRepertoires[1];
        repertoireEtudiants = sousRepertoires[2];
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();
        agentsDisplay = new javax.swing.JLabel();
        teacherDisplay = new javax.swing.JLabel();
        studentDisplay = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        agentsTable = new javax.swing.JTable();
        studentScrollable = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Affichage de Contacts");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setText("Revenir");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 650, -1, -1));

        agentsDisplay.setText("Affichage des Agents");
        getContentPane().add(agentsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 6, -1, 24));

        teacherDisplay.setText("Affichage des Enseignants");
        getContentPane().add(teacherDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 318, -1, -1));

        studentDisplay.setText("Affichage des Etudiants");
        getContentPane().add(studentDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 318, -1, -1));

        agentsTable.setModel(new javax.swing.table.DefaultTableModel(
            repertoireAgents,
            repertoireAgentsLabel
        ));
        jScrollPane1.setViewportView(agentsTable);

        jScrollPane4.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 37, 937, 263));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            repertoireEtudiants,
            repertoireEtudiantsLabel
        ));
        jScrollPane2.setViewportView(studentTable);

        studentScrollable.setViewportView(jScrollPane2);

        getContentPane().add(studentScrollable, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 359, 540, 286));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            repertoireEnseignants,
            repertoireEnseignantsLabel
        ));
        jScrollPane3.setViewportView(jTable3);

        jScrollPane5.setViewportView(jScrollPane3);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 359, 500, 286));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        mainFrmApplication.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactsDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactsDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactsDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactsDisplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactsDisplayFrame(new Repertoire()).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agentsDisplay;
    private javax.swing.JTable agentsTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel studentDisplay;
    private javax.swing.JScrollPane studentScrollable;
    private javax.swing.JTable studentTable;
    private javax.swing.JLabel teacherDisplay;
    // End of variables declaration//GEN-END:variables

}
