CREATE DATABASE IF NOT EXISTS contacts_db;

USE contacts_db;

CREATE TABLE IF NOT EXISTS Agent (
    code VARCHAR(6) NOT NULL PRIMARY KEY, nom VARCHAR(20) NOT NULL, dateNaissance DATE NOT NULL, address VARCHAR(20) NOT NULL, email VARCHAR(20) NOT NULL, telNumber VARCHAR(10) NOT NULL, salaire DECIMAL(10, 2) NOT NULL, statut VARCHAR(10) NOT NULL, categorie VARCHAR(10) NOT NULL, indiceSalaire INT NOT NULL, occupation VARCHAR(10) NOT NULL
)

CREATE TABLE IF NOT EXISTS Enseignant (
    code VARCHAR(6) NOT NULL PRIMARY KEY, nom VARCHAR(20) NOT NULL, dateNaissance DATE NOT NULL, address VARCHAR(20) NOT NULL, email VARCHAR(20) NOT NULL, telNumber VARCHAR(10) NOT NULL, statut VARCHAR(10) NOT NULL
)

CREATE TABLE IF NOT EXISTS Etudiant (
    code VARCHAR(6) NOT NULL PRIMARY KEY, nom VARCHAR(20) NOT NULL, dateNaissance DATE NOT NULL, address VARCHAR(20) NOT NULL, email VARCHAR(20) NOT NULL, telNumber VARCHAR(10) NOT NULL, cycle VARCHAR(10) NOT NULL, niveau VARCHAR(10) NOT NULL
)